<?php
/**
 * Database Configuration - The Trendy Station
 * Auto-generated by setup script with helper functions
 */

$config = [
    'host' => 'localhost',
    'dbname' => 'trendy_station', 
    'username' => 'root',
    'password' => '',
    'charset' => 'utf8mb4',
    'options' => [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]
];

// Create PDO connection
try {
    $dsn = "mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}";
    $pdo = new PDO($dsn, $config['username'], $config['password'], $config['options']);
      // Set charset and timezone
    $pdo->exec("SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci");
    $pdo->exec("SET time_zone = '+07:00'"); // Vietnam timezone
    
    // Set PHP timezone to match
    date_default_timezone_set('Asia/Ho_Chi_Minh');
    
} catch (PDOException $e) {
    die('Database connection failed: ' . $e->getMessage());
}

/**
 * Function helper để thực hiện query
 */
function executeQuery($sql, $params = []) {
    global $pdo;
    try {
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        return $stmt;
    } catch (PDOException $e) {
        die("❌ Lỗi thực hiện query: " . $e->getMessage());
    }
}

/**
 * Function lấy tất cả records
 */
function fetchAll($sql, $params = []) {
    $stmt = executeQuery($sql, $params);
    return $stmt->fetchAll();
}

/**
 * Function lấy 1 record
 */
function fetchOne($sql, $params = []) {
    $stmt = executeQuery($sql, $params);
    return $stmt->fetch();
}

/**
 * Function đếm số records
 */
function countRecords($table, $where = '1=1', $params = []) {
    $sql = "SELECT COUNT(*) as total FROM $table WHERE $where";
    $result = fetchOne($sql, $params);
    return $result['total'];
}

/**
 * Function tạo mã code tự động
 */
function generateCode($prefix, $table, $column) {
    $sql = "SELECT MAX(CAST(SUBSTRING($column, " . (strlen($prefix) + 1) . ") AS UNSIGNED)) as max_num 
            FROM $table 
            WHERE $column LIKE '$prefix%'";
    $result = fetchOne($sql);
    $nextNum = ($result['max_num'] ?? 0) + 1;
    return $prefix . str_pad($nextNum, 3, '0', STR_PAD_LEFT);
}

// Test kết nối
if (isset($_GET['test_db'])) {
    try {
        $result = fetchOne("SELECT 'Kết nối thành công!' as message, NOW() as current_time");
        echo "✅ " . $result['message'] . " - " . $result['current_time'];
    } catch (Exception $e) {
        echo "❌ Lỗi test: " . $e->getMessage();
    }
    exit;
}
?>